### ISSUE TITLE
html organization

### ISSUE THREAD

**Issue by rimmesbe** [codefullstack/prj-rev-bwfs-dasmoto#1]
So looking at this html it just looks like one giant block of code. Use div's to structure your html into sections. Then add the id or class from the h2 onto the div as a section label and easy access to all elements within the section:
.brushes h2 { }
<img width="122" alt="screen shot 2017-06-28 at 1 57 34 pm" src="https://user-images.githubusercontent.com/9957628/29623494-9678d876-87f4-11e7-8cf4-117b077b641c.png">

https://github.com/codefullstack/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L12-L15

**Comment by codefullstack** [comment]
Hi! Thank you so much for this valuable feedback. Looking back, it's indeed better to work with div's per section.
