### ISSUE TITLE
alt attribute

### ISSUE THREAD

**Issue by rimmesbe** [codefullstack/prj-rev-bwfs-dasmoto#5]
Try to get in the habit of adding an alt attribute description to your image tags. Makes your code more assessable and makes your code look more professional. 

https://github.com/codefullstack/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L13

**Comment by codefullstack** [comment]
that's a good tip, didn't learnt it but will definitely incorporate it :)
